---

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - libpq-dev
    - python-dev
    - python-pip
    - python-pycurl
    - supervisor
  tags: packages

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages

- name: Update CA Certificates
  shell: /usr/sbin/update-ca-certificates

- name: Create common directories
  file:
    path: "{{ item.path }}"
    state: "{{ item.state | default('directory') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: 0755
  with_items: common_directories

- name: upload sudo config for key forwarding as root
  copy:
    src: ssh_key_forward
    dest: /etc/sudoers.d/ssh_key_forward
    validate: 'visudo -c -f %s'
    owner: root
    group: root
    mode: 0440

- name: update /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
  when: COMMON_HOSTNAME|length > 0
  register: etc_hosts

- name: update /etc/hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
  when: COMMON_HOSTNAME|length > 0
  register: etc_hostname

- name: run hostname
  shell: hostname -F /etc/hostname
  when: COMMON_HOSTNAME|length >0 and (etc_hosts.changed or etc_hostname.changed)

- name: update /etc/dhcp/dhclient.conf
  template:
    src: etc/dhcp/dhclient.conf.j2
    dest: /etc/dhcp/dhclient.conf
  when: COMMON_CUSTOM_DHCLIENT_CONFIG

- name: Copy the templates to their respestive destination
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: "{{ item.mode | default(644) }}"
  with_items:
    - { src: 'edx_rsyslog.j2', dest: '/etc/rsyslog.d/99-edx.conf' }
    - { src: 'etc/logrotate.d/hourly/edx_logrotate.j2', dest: '/etc/logrotate.d/hourly/edx-services' }
    - { src: 'etc/cron.hourly/logrotate.j2', dest: '/etc/cron.hourly/logrotate', mode: '555' }
    - { src: 'etc/logrotate.d/hourly/edx_logrotate_tracking_log.j2', dest: '/etc/logrotate.d/hourly/tracking.log' }
    - { src: '{{ COMMON_MOTD_TEMPLATE }}', dest: '/etc/motd.tail', mode: '755' }
    - { src: 'sshd_config.j2', dest: '/etc/ssh/sshd_config' }
  notify:
    - restart ssh
    - restart rsyslogd


